services:
  rabbitmq:
    image: rabbitmq:management
    container_name: bike_rental_mq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672" 
    restart: always 

  db:
    image: mysql
    hostname: mysql_log
    container_name: log-bike-rentals
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=log_bikerentals
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-volume:
    driver: local
    