version: '3.5'

services:
  bike_rental_payment_pg:
      image: postgres:16-alpine
      container_name: bike_rental_payment_pg
      hostname: bike_rental_payment_pg
      ports:
        - "5435:5432"
      environment:
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_USER=root"
        - "POSTGRES_DB=bike_rentals-payment_db"
        - "PGDATA=/var/lib/postgresql/data/pgdata"
      volumes:
      - "bike_rentals_payment_db_volume:/var/lib/postgresql/data/pgdata"

  rabbitmq:
    image: rabbitmq:management
    container_name: bike_rental_mq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672" 
    restart: always 

  

     
volumes:
  bike_rentals_payment_db_volume:
