version: '3.8'

services:
  db:
    image: mysql
    hostname: mysql_log
    container_name: log-bike-rentals
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=log_bikerentals
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-volume:
    driver: local
    